// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZyfQWwme5rbOnI8OAHwqzp3uguVH4vVk',
    appId: '1:739249475158:web:df30385eea54e7fc9c35f7',
    messagingSenderId: '739249475158',
    projectId: 'appproyectocrazytaxi',
    authDomain: 'appproyectocrazytaxi.firebaseapp.com',
    storageBucket: 'appproyectocrazytaxi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUOunAGY8s3SlWa_CAuvtwZzTr7jWcG0I',
    appId: '1:739249475158:android:6bb9fd1af405eb759c35f7',
    messagingSenderId: '739249475158',
    projectId: 'appproyectocrazytaxi',
    storageBucket: 'appproyectocrazytaxi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUw00lvA_2CUG-uTDDpDR9WQvZ7WDNJ-o',
    appId: '1:739249475158:ios:594f2290278478d89c35f7',
    messagingSenderId: '739249475158',
    projectId: 'appproyectocrazytaxi',
    storageBucket: 'appproyectocrazytaxi.appspot.com',
    iosClientId: '739249475158-d94un3mj98ed4c8hbn9f4g7ae8c7jacj.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTaxis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUw00lvA_2CUG-uTDDpDR9WQvZ7WDNJ-o',
    appId: '1:739249475158:ios:594f2290278478d89c35f7',
    messagingSenderId: '739249475158',
    projectId: 'appproyectocrazytaxi',
    storageBucket: 'appproyectocrazytaxi.appspot.com',
    iosClientId: '739249475158-d94un3mj98ed4c8hbn9f4g7ae8c7jacj.apps.googleusercontent.com',
    iosBundleId: 'com.example.appTaxis',
  );
}
